blueprint:
  name: Camera Event Notification (no AI)
  author: MF
  homeassistant:
    min_version: 2024.10.0
  description: >
    Sendet Benachrichtigungen bei Kamera-Ereignissen – mit Snapshot oder Live-Vorschau – ganz ohne AI-Analyse.
    Unterstützt dynamische/konsolidierte Zustellung, frei wählbares Ziel-Dashboard, Android/iOS-Optionen
    und optional TTS.
  domain: automation
  source_url: https://github.com/michaelf988/ha-cam-snapshot/edit/main/ha-cam-snapshot.yaml

  input:
    # Laufbedingungen & Cooldown
    run_conditions:
      name: Run Conditions
      description: Alle Bedingungen müssen erfüllt sein, damit die Automatisierung läuft.
      default: []
      selector:
        condition:
    cooldown:
      name: Cooldown
      description: Wartezeit, bevor die Automatisierung erneut laufen darf (empfohlen für belebte Bereiche).
      default:
        minutes: 10
      selector:
        duration: {}

    # Kamera & Sensoren
    camera_sensor_section:
      name: Camera & Sensor Settings
      description: Einstellungen für Kameras und (optional) Bewegungssensoren.
      icon: mdi:camera
      collapsed: false
      input:
        camera_entities:
          name: Camera Entities
          description: Eine oder mehrere Kameras.
          default: []
          selector:
            entity:
              multiple: true
              filter:
                domain: camera
        trigger_state:
          name: Trigger State
          description: Auslöser, wenn eine Kamera diesen Zustand annimmt (z. B. 'recording').
          default: 'recording'
          selector:
            text:
              multiline: false
        motion_sensors:
          name: Motion Sensors (optional)
          description: Nutze Binary-Sensoren, wenn deine Kameras ihren Zustand nicht ändern (z. B. Frigate).
          default: []
          selector:
            entity:
              multiple: true
              filter:
                domain: binary_sensor

    # Benachrichtigungen
    notification_section:
      name: Notification Settings
      description: Zielgeräte, Zustellart, Vorschau & Darstellungsoptionen.
      icon: mdi:message-badge
      collapsed: false
      input:
        notify:
          name: Enable Notifications
          description: Benachrichtigungen senden?
          default: true
          selector:
            boolean:
        condition_notify:
          name: Condition to Notify
          description: Zusätzliche Bedingung(en) NUR für das Senden der Benachrichtigung.
          default: []
          selector:
            condition:
        notify_device:
          name: Notify Device(s)
          description: Zielgeräte (Home Assistant Companion App).
          default: []
          selector:
            device:
              multiple: true
              filter:
                integration: mobile_app
        notification_delivery:
          name: Notification Delivery
          description: "Dynamic (sofort) oder Consolidated (kurze Sammelverzögerung)."
          default: 'Dynamic'
          selector:
            select:
              options:
                - label: Dynamic
                  value: 'Dynamic'
                - label: Consolidated
                  value: 'Consolidated'
        preview_mode:
          name: Preview Mode
          description: Snapshot (Bild) oder Live Preview (Live-Feed in der Notification).
          default: 'Snapshot'
          selector:
            select:
              options:
                - label: Snapshot
                  value: 'Snapshot'
                - label: Live Preview
                  value: 'Live Preview'
        notification_time:
          name: Time Format in Title (optional)
          description: Füge die aktuelle Uhrzeit in den Titel ein (12/24h) – oder leer lassen.
          default: ''
          selector:
            select:
              options:
                - label: No Time Added
                  value: ''
                - label: 12 Hour
                  value: 'at {{ now().strftime("%I:%M %p") }}'
                - label: 24 Hour
                  value: 'at {{ now().strftime("%H:%M") }}'
        # Pfad für Snapshot-Datei (für Dynamic+Snapshot)
        file_path:
          name: File Path (Snapshot)
          description: >
            Speicherort für das aktuelle Snapshot-Bild.
            Tipp: „Media Folder – Secured“ nutzt /media (sicherer), „Public – Unsecured“ nutzt /config/www (öffentlich).
          default: '/media/snapshots/{{ camera_file_path }}/last_motion.jpg'
          selector:
            select:
              options:
                - label: Media Folder - Secured
                  value: '/media/snapshots/{{ camera_file_path }}/last_motion.jpg'
                - label: Public Folder - Unsecured
                  value: '/config/www/snapshots/{{ camera_file_path }}/last_motion.jpg'
              custom_value: true
        tap_navigate:
          name: Tap Navigate
          description: Lovelace-Pfad, der beim Öffnen der Benachrichtigung geöffnet wird (z. B. /lovelace/cameras).
          default: /lovelace/0
          selector:
            text:
              multiline: false
        # Notification Cooldown
        delay_notification:
          name: Notification Cooldown (seconds)
          description: Wartezeit in Sekunden zwischen zwei Benachrichtigungen.
          default: 60
          selector:
            number:
              min: 0
              max: 86400
              unit_of_measurement: seconds

        # Android
        notification_sticky:
          name: Sticky Notification (Android)
          default: true
          selector:
            boolean:
        notification_color:
          name: Notification Accent Color (Android)
          default: '#03a9f4'
          selector:
            select:
              options:
                - label: Blue - #03a9f4
                  value: '#03a9f4'
                - label: Red - #f44336
                  value: '#f44336'
                - label: Green - #4caf50
                  value: '#4caf50'
                - label: White - #ffffff
                  value: '#ffffff'
              custom_value: true
              sort: false
              multiple: false
        notification_icon:
          name: Status Bar Icon (Android)
          default: mdi:cctv
          selector:
            icon:
              placeholder: mdi:cctv
        notification_channel:
          name: Custom Notification Channel (Android)
          description: >
            Eigener Kanalname oder „alarm_stream“ für lauten Alarm. (Standard = Kameraname + „Snapshot“)
          default: '{{ camera }} Snapshot'
          selector:
            select:
              options:
                - label: Camera Name
                  value: '{{ camera }} Snapshot'
                - label: Alarm
                  value: alarm_stream
              custom_value: true

        # iOS
        notification_sound:
          name: iOS Sound
          default: default
          selector:
            text:
              multiline: false
        notification_volume:
          name: iOS Sound Volume (0..1)
          default: 1
          selector:
            number:
              min: 0
              max: 1
              step: 0.1
        notification_critical:
          name: iOS Critical Alert
          default: false
          selector:
            boolean:

        # Optional TTS (Android)
        tts_notification:
          name: TTS on Android
          default: false
          selector:
            boolean:
        tts_volume:
          name: TTS Volume Stream (Android)
          default: notification_stream
          selector:
            select:
              options:
                - label: Notification Stream
                  value: notification_stream
                - label: Alarm Stream
                  value: alarm_stream
                - label: Alarm Stream (Max)
                  value: alarm_stream_max
        condition_notify_tts:
          name: Condition(s) for TTS (optional)
          default: []
          selector:
            condition:

    # (Optional) Weitere Aktionen
    experimental_section:
      name: Additional Actions
      description: Optionale, eigene Aktionen NACH der Benachrichtigung.
      icon: mdi:playlist-plus
      collapsed: true
      input:
        additional_actions:
          name: Additional Actions
          description: Diese Aktionen werden nach der Benachrichtigung ausgeführt.
          default: []
          selector:
            action:

# ================= Variables =================
variables:
  cooldown: !input cooldown
  preview_mode: !input preview_mode

  # Geräte / Notification
  notify_devices: !input notify_device
  notification_delivery: !input notification_delivery
  notification_sticky: !input notification_sticky
  notification_color: !input notification_color
  notification_icon: !input notification_icon
  notification_channel: !input notification_channel
  notification_sound: !input notification_sound
  notification_volume: !input notification_volume
  notification_critical: !input notification_critical
  delay_notification: !input delay_notification

  # Kamera & Pfade
  camera_entities_list: !input camera_entities
  motion_sensors_list: !input motion_sensors
  file_path: !input file_path
  snapshot_access_file_path: '{{ file_path | replace(''/config/www'', ''/local'') | replace(''/media'', ''/media/local'') }}'

  # Anzeige
  notification_time: !input notification_time
  label: Motion detected

  # Helfer
  camera_entity: >
    {% if motion_sensors_list and not trigger.entity_id.startswith("camera") %}
      {% set index = motion_sensors_list.index(trigger.entity_id) %}
      {{ camera_entities_list[index] }}
    {% else %}
      {{ trigger.entity_id }}
    {% endif %}
  camera_entity_snapshot: >
    {{ camera_entities_list[0] }}
  camera_file_path: >
    {{ camera_entity_snapshot.replace("camera.", "")}}
  camera: >
    {{ camera_entities_list[0].replace("camera.", "").replace("_", " ") | title }}
  tag: >
    {{ camera_entity + int(as_timestamp(now()))|string }}
  device_name_map: >
    {% set ns = namespace(device_names=[]) %}
    {% for device_id in notify_devices %}
      {% set device_name = device_attr(device_id, "name") %}
      {% set sanitized_name = "mobile_app_" + device_name | slugify  %}
      {% set ns.device_names = ns.device_names + [sanitized_name] %}
    {% endfor %}
    {{ ns.device_names }}

# ================= Meta =================
max_exceeded: silent
mode: single

# ================= Triggers =================
triggers:
  - trigger: state
    entity_id: !input camera_entities
    to: !input trigger_state
    id: camera_trigger
  - trigger: state
    entity_id: !input motion_sensors
    to: 'on'
    id: motion_sensor_trigger

# ================= Conditions =================
condition:
  - condition: and
    conditions: !input run_conditions

# ================= Actions =================
action:
  # Nur benachrichtigen, wenn aktiviert + Bedingungen erfüllt + Cooldown passt
  - if:
      - condition: template
        value_template: !input notify
    then:
      - if:
          - condition: !input condition_notify
        then:
          - if:
              - condition: template
                value_template: >
                  {{ not this.attributes.last_triggered or
                     (now() - this.attributes.last_triggered).seconds > delay_notification }}
            then:
              - choose:
                  # ---------- Dynamic Delivery ----------
                  - conditions:
                      - condition: template
                        value_template: "{{ notification_delivery == 'Dynamic' }}"
                    sequence:
                      - choose:
                          # Snapshot
                          - conditions:
                              - condition: template
                                value_template: "{{ preview_mode == 'Snapshot' }}"
                            sequence:
                              # Snapshot von der ersten Kamera speichern (stabiler Dateiname)
                              - service: camera.snapshot
                                target:
                                  entity_id: "{{ camera_entity_snapshot }}"
                                data:
                                  filename: !input file_path

                              - alias: "Send instant notification (Snapshot)"
                                repeat:
                                  for_each: "{{ device_name_map }}"
                                  sequence:
                                    - action: "notify.{{ repeat.item }}"
                                      data:
                                        title: "{{ label }} {{ notification_time }}"
                                        message: "{{ camera }} has detected activity."
                                        data:
                                          url: !input tap_navigate          # iOS
                                          clickAction: !input tap_navigate  # Android
                                          tag: "{{ tag }}"
                                          group: !input notification_channel
                                          alert_once: true
                                          # Priorität
                                          ttl: 0
                                          priority: high
                                          # Android
                                          channel: !input notification_channel
                                          color: !input notification_color
                                          notification_icon: !input notification_icon
                                          sticky: !input notification_sticky
                                          image: "{{ snapshot_access_file_path }}"
                                          # iOS
                                          attachment:
                                            url: "{{ snapshot_access_file_path }}"
                                            content_type: JPEG
                                          push:
                                            interruption-level: 'active'
                                            sound:
                                              name: !input notification_sound
                                              volume: !input notification_volume
                                              critical: !input notification_critical

                          # Live Preview
                          - conditions:
                              - condition: template
                                value_template: "{{ preview_mode == 'Live Preview' }}"
                            sequence:
                              - alias: "Send instant notification (Live Preview)"
                                repeat:
                                  for_each: "{{ device_name_map }}"
                                  sequence:
                                    - action: "notify.{{ repeat.item }}"
                                      data:
                                        title: "{{ label }} {{ notification_time }}"
                                        message: "{{ camera }} has detected activity."
                                        data:
                                          entity_id: "{{ camera_entity }}"
                                          url: !input tap_navigate
                                          tag: "{{ tag }}"
                                          group: !input notification_channel
                                          alert_once: true
                                          ttl: 0
                                          priority: high
                                          push:
                                            interruption-level: 'active'
                                            sound:
                                              name: !input notification_sound
                                              volume: !input notification_volume
                                              critical: !input notification_critical

                  # ---------- Consolidated Delivery ----------
                  - conditions:
                      - condition: template
                        value_template: "{{ notification_delivery == 'Consolidated' }}"
                    sequence:
                      - choose:
                          - conditions:
                              - condition: template
                                value_template: "{{ preview_mode == 'Snapshot' }}"
                            sequence:
                              - service: camera.snapshot
                                target:
                                  entity_id: "{{ camera_entity_snapshot }}"
                                data:
                                  filename: !input file_path
                      - delay: "00:00:05"
                      - alias: "Send consolidated notification"
                        repeat:
                          for_each: "{{ device_name_map }}"
                          sequence:
                            - action: "notify.{{ repeat.item }}"
                              data:
                                title: "{{ label }} {{ notification_time }}"
                                message: "{{ camera }} has detected activity."
                                data:
                                  url: !input tap_navigate
                                  clickAction: !input tap_navigate
                                  tag: "{{ tag }}"
                                  group: !input notification_channel
                                  alert_once: true
                                  ttl: 0
                                  priority: high
                                  channel: !input notification_channel
                                  color: !input notification_color
                                  notification_icon: !input notification_icon
                                  sticky: !input notification_sticky
                                  {% raw %}{% if preview_mode == 'Snapshot' %}{% endraw %}
                                  image: "{{ snapshot_access_file_path }}"
                                  attachment:
                                    url: "{{ snapshot_access_file_path }}"
                                    content_type: JPEG
                                  {% raw %}{% endif %}{% endraw %}
                                  push:
                                    interruption-level: 'active'
                                    sound:
                                      name: !input notification_sound
                                      volume: !input notification_volume
                                      critical: !input notification_critical

      # ---------- Optional: TTS auf Android ----------
      - if:
          - condition: template
            value_template: !input tts_notification
        then:
          - if:
              - condition: !input condition_notify_tts
            then:
              - alias: "TTS Notification (Android)"
                repeat:
                  for_each: "{{ device_name_map }}"
                  sequence:
                    - action: "notify.{{ repeat.item }}"
                      data:
                        message: TTS
                        data:
                          ttl: 0
                          priority: high
                          media_stream: !input tts_volume
                          tts_text: "{{ camera }} has detected activity."

  # ---------- Allgemeiner Cooldown ----------
  - delay: !input cooldown
